name = "postgrestui-downloads"
main = "worker.ts"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[routes]]
pattern = "dl-postgrestui.voltrus.id"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "postgrestui-releases-db"
database_id = "8e3dd46c-dc36-4938-9dc2-c0e601a610b5"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "postgrestui-releases"
